intel/ikgt-core

vmm/vmexit/vmexit_cpuid.c

output:
EAX: Max basic leaf supported
EBX~EDX: EVMM Signature
Change-Id: I2b6a8a48ba881776e29f9dbc748e512ee4a8f665
Signed-off-by: Qi, Yadong <yadong.qi@intel.com>

[VMM] Filter CPUID: leaf=0x40000000

---

include/evmm_desc.h
include/file_pack.h
include/vmm_asm.h
loader/stage0/abl/stage0.c
loader/stage0/abl_cl/stage0.c
loader/stage0/abl_osloader/stage0.c
loader/stage0/efi/stage0.c
loader/stage0/sbl/seed_list_parse.c
loader/stage0/stage0_lib/stage0_lib.c
packer/evmm_packer.c
product/celadon_64.cfg
product/celadon_apl.cfg
product/celadon_clk.cfg
product/celadon_kbl.cfg
product/feature/trusty_tee.cfg
readme.txt
vmm/guest/gcpu_state.c
vmm/include/modules/security_info.h
vmm/include/modules/template_tee.h
vmm/include/modules/trusty_tee.h
vmm/main.c
vmm/modules/nested_vt/emulate_vmentry.c
vmm/modules/nested_vt/emulate_vmexit.c
vmm/modules/optee_guest/optee_guest.c
vmm/modules/security_info/Makefile
vmm/modules/security_info/security_info.c
vmm/modules/trusty_guest/trusty_guest.c
vmm/modules/trusty_tee/Makefile
vmm/modules/trusty_tee/trusty_info.h
vmm/modules/trusty_tee/trusty_tee.c

The patches upstream is for 
add memory barrier when scrub sensetive data.
refine build flag
refine handle VMEXIT_OTHERS
add module of Trusty based on template tee framework
Signed-off-by: Sheng Wei w.sheng@intel.com

Trusty patches upstream

---

product/celadon_64.cfg
product/celadon_apl.cfg
product/celadon_clk.cfg
product/celadon_kbl.cfg
vmm/modules/trusty_tee/trusty_tee.c

Add switches to enable security_test module and disable VTD module.
Then we can append SECURITY_TEST=true and DISABLE_VTD=true as
parameters after android make command.
Change-Id: I87474a4d6af2194bd384584bed8a8ca24b331bde
Signed-off-by: Duan Honghui <Honghuix.duan@intel.com>

Add config for security test.

---

vmm/modules/vtd/vtd_mem_map.c

Insert 4K page in translation table when VT-d only support 3-level
page-table to force initialize PDPT.

vmm: vtd: initialize VT-d translation table for 3-level page-table

---

include/lib/mp_init.h
lib/mp_init/mp_init.c
vmm/modules/suspend/suspend.c

Do not reserve a 4K page for suspend feature support.
Save SIPI page memory before suspend and restore the SIPI
page memory after resume.

vmm: suspend: refine suspend logic

---

vmm/modules/perf_ctrl_isolation/perf_ctrl_isolation.c

No assert when cpu does not support IA32_PERF_GLOBAL_CTRL load/store
on vmentry/vmexit. Replace the assertion with warning log.

vmm: refine perf_ctrl_isolation module

---

loader/stage0/abl/stage0_entry.S
loader/stage0/abl_cl/stage0_entry.S
loader/stage0/grub-qemu/stage0_entry.S
loader/stage0/sbl/stage0_entry.S

Some old version of GCC/GNU AS does not support "ULL"
suffix in assemble file.

loader: remove ULL suffix from assembly file

---

loader/stage0/entry/entry_asm.h

"ULL" suffix should be removed from macro definition to
adapt some old version of GCC/GNU AS.
Signed-off-by: Zhong,Fangjian <fangjian.zhong@intel.com>

loader: remove ULL suffix from assembly header file

---

lib/print/serial.c
vmm/modules/l1tf/l1tf.c
vmm/modules/perf_ctrl_isolation/perf_ctrl_isolation.c
vmm/utils/lock.c

vmm: add line break for some warning logs
vmm: lock: enlarge DEADLOCK_CYCLE
lib: print: fix compiling issue of unused function

Minor fix civ

---

loader/stage0/efi/efi_boot_param.c
vmm/modules/trusty_tee/trusty_tee.c

Memory address and size of VMM/Trusty should be 2M Bytes algin
Signed-off-by: Chen Gang G <gang.g.chen@intel.com>

vmm: memory address and size must be 2MB algin on efi bootloader

---

loader/stage1/stage1.c
packer/Makefile
packer/evmm_packer.c
packer/readme.txt
readme.txt
vmm/guest/gcpu_state.c
vmm/include/modules/security_info.h
vmm/modules/security_info/security_info.c
vmm/modules/trusty_tee/trusty_info.h
vmm/modules/trusty_tee/trusty_tee.c

New hypercall is introduced to get secinfo for Trusty TEE guest.
With this change, eVmm stores secinfo which provided by bootloader, and
copies secinfo to Trusty TEE memory region. Trusty TEE guest can also
invoke hypercall to get secinfo from eVMM.
This hypercall can only be invoked from Trusty TEE guest for only one
time. And eVmm would erase secinfo once Trusty TEE guest invoked this
hypercall.
Signed-off-by: Zhong,Fangjian <fangjian.zhong@intel.com>

vmm: Add get secinfo vmcall and update Trusty boot environment from 32-bit to 64-bit

---

Makefile
loader/stage0/entry/entry_64.S
loader/stage0/entry/linker.lds

make: add -delete-null-pointer-checks only for higher version(>6) clang
loader: fix link issue for lower version of ld.lld
loader: fix link issue for lld(version >= 9)

Fix LLVM related build issue

---

lib/image_loader/elf_ld/elf_ld.c

The local variable must be initialized before use.
Signed-off-by: Qi, Yadong <yadong.qi@intel.com>

lib: initialize local variable before use

---

product/celadon_64.cfg

Currently, workaround the INIT signal missing for CiV. In future,
We may remove this workaround if KVM has formal fix of emulating
INIT/SIPI vmexit to L2 Hypervisor.
Signed-off-by: Qi, Yadong <yadong.qi@intel.com>

Enable workaround for INIT missing

---

product/cic.cfg

Seperate config for CiC due to VT-d issue on CometLake NUC.
Signed-off-by: Qi, Yadong <yadong.qi@intel.com>

Add config for CiC

---

vmm/guest/gcpu_state.c

Remove the workaround for KVM when reset gcpu state.

vmm: remove the workaround for KVM when reset gcpu state

---

vmm/modules/suspend/suspend.c

Must use hlt-loop/busy-loop to stop CPU. This is because the CPU might
be waked up if there is a lapic timer set before suspend especially running
on top of KVM.

Replace halt with halt-loop when suspend APs

---

include/vmm_base.h
packer/Makefile

This is required to enable setup path for
Android 11
Tracked-On: OAM-95316
Signed-off-by: yaravapa <yasoda.aravapalli@intel.com>

Use prebuilts clang instead of gcc to build evmmpacker

---

vmm/include/modules/acpi.h
vmm/modules/suspend/acpi_pm.c
vmm/modules/suspend/acpi_pm.h
vmm/modules/suspend/suspend.c

According to ACPI Spec Chapter 5.2.9 Fixed ACPI Description Table:
If X_PM1a_CNT_BLK field contains a non zero value which can be used by the OSPM,
then PM1a_CNT_BLK must be ignored by the OSPM.
The PM1a/b_CNT block parsing logic is revisited in this patch.
Add assumptions/asserts when parsing PM1 control block:
1. The control register block type is IO, assert on MMIO/MEM. May need revisit.
2. X_FW_WAKING_VECTOR is not used since we do not support 32/64 waking entry.
May need revisit.

vmm: suspend: refine ACPI/FADT parse

---

loader/stage0/grub-qemu/linker.lds

With Clang verison r416183c1, global variable of serial port device
resides in data section. However, data section is omiited in stage0
linker script.
In this case, when we init serial port device, data section will be
touched. Since there is no data section, and stage1 raw binary is
appended to stage0 raw binary, then file header of stage1 is
overwritten.
To fix this issue, we specify .data section to .text section.

Fix stage0 loads stage1 binary failure

---

readme.txt
vmm/main.c
vmm/modules/vtd/vtd.c

Add function to detect whether translation is already enabled by
BIOS, if yes, then do not activate VT-d at boot stage.

vtd: refine vtd late activate process

---

lib/print/serial.c

Since the stage0/entry will only keep the code segment and strip
all other segment, so the global variable in serial will be also
been stripped when linked to stage0/entry.
In this patch, set attribute of g_ser_dev to make it always in
".text" segment so it wont be stripped when linked to stage0/entry.

Fix hang issue when serial enabled

---

packer/evmm_packer.c
vmm/modules/msr_monitor/msr_monitor.c
vmm/utils/heap.c

1. fix potential buffer overflow in heap.c
2. add assert when do hva_to_hpa in msr_monitor.c
3. fix unchecked return of fread()

Fix static scan issues
